# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce81b8fed8b7a3a959d8f36f672af92c"
name = "EQXPlus Checkout UI Stage"
handle = "eqxplus-checkout-ui-stage"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "equinoxplus-develop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products, write_delivery_customizations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
